### ISSUE TITLE
Error: 'user_stats_clear_achievement' (a nil value)

### ISSUE THREAD

**Issue by Qwarr** [defold/extension-steam#4] opened 2023-11-06 21:56 UTC
Seems `steam.user_stats_clear_achievement(name)` isn't working: 

`attempt to call field 'user_stats_clear_achievement' (a nil value)`

**Comment by JCash** [comment] 2023-11-07 07:36
Seems like a duplicate of https://github.com/defold/extension-steam/issues/3

**Closed** 2023-11-07 09:36 UTC
